---
title: Semantic Editing in Word Processors
subtitle: |
  | CPSC 490
  | Final Report
author: Hristo Staykov
advisor: Prof. Holly Rushmeier
institute: |
  | Department of Computer Science
  | Yale University
date: Spring 2021

abstract: |
  Text selection in word processors is ordinarily done using a pointing device or the keyboard arrow cluster, and can be precisely defined on a character basis. However, such precision is unnecessary if user thinks of the text as a string of words or sentences. It can impose a burden when the user is trying to select a complete sentence, but has to point to the exact start and end of the desired selection. This can be particularly troublesome on mobile devices with limited screen space.

  This project explores how tools from the NLP community can aid the user in editing text by guiding their selections. There already exist shortcuts for selecting single words or the entirety of the text, but, to the author's knowledge, there are no tools which allow for quick selection of sentences, embeded sentences, and constituents in natural language.

  This project implements a simple text editor that processes text using a constituency parser. Employing the text's hierarchical structure, this editor augments various familiar interfaces for selecting text, and to proposes a few new ones. Moreover, the editor provides visual hints towards the structure of the text in the form of syntax highlighting, which in our testing facilitated skim-reading and guided the user when selecting text.

bibliography: biblio.bib
documentclass: report
top-level-division: section
biblio-style: numeric
header-includes: |
    \usepackage[caption = false]{subfig}
    \usepackage{color,soul}
    \usepackage[os=mac]{menukeys}
    \sethlcolor{lightgray}
    \usepackage{forest}
    \usepackage{tikz}
    \usepackage{lscape}
    \usepackage{changepage}
    \usepackage{CJKutf8}
include-before: |
    \input{./tex/parse_fig.tex}
---
